### ISSUE TITLE
Meeting notes

### ISSUE THREAD

**Issue by ulde01** [sebgroup/design-library#126]
Notes from community meetings, etc.

**Comment by ulde01** [comment]
### Future of component libraries, meeting 2020-05-12 - notes
**Agenda**
- Background and why a design system
- Concept of Design Library and communities contributing
- Ulrika’s vision
- Obstacles today
- How should it work
- Todo’s

**Purpose of meeting**
See how front-end development and design can work better together with common components.

**Notes**
Find the meeting notes here: [Future of component libraries.docx](https://github.com/sebgroup/design-library/files/4696068/Future.of.component.libraries.docx)

**Comment by ulde01** [comment]
### First meeting with FE frameworks coordination team, 2020-05-28

**Agenda** 
1.	Practicalities
2.	Why we do this
3.	Purpose of this team
4.	Target groups
5.	Topics to address
6.	What’s next

**Notes**
[FE frameworks co-ordination.docx](https://github.com/sebgroup/design-library/files/4696131/FE.frameworks.co-ordination.docx)

**Practicalities**
- Slack-channel #design-library-dev
- Backlog and issues https://github.com/sebgroup/design-library/projects/3
- Meetings every other week on Thursdays 11 am (CEST)

**Todo's**
- [x] Everyone looks into time allocation - everyone
- [x] Find a FE architect contact - Leopold
- [x] Add topics to Github - Ulrika + everyone

**Comment by ulde01** [comment]
### FE frameworks coordination team, 2020-06-11
(I will start adding our meeting notes in Slack, now when we are up and running)
**Present**: Joacim, Robert, Karolis, Yousif, Leopold and Ulrika

- Quick **recap** from our meeting May 27.
- **Bootstrap** information. Roberts contract might come to an end, to be continued.
- Todo's follow-up: **Time allocation** as it looks at the moment: Joacim (part of Thursdays and Fridays), Robert (up to 100%), Karolis (almost 0 % during the next 2 mts), Yousif (10-20%), Leopold (10%), Ulrika (0-100%)
- Todo's follow-up: Leopold contacted two **architects** with FE-focus and we will have a coffee with them to see how they want to be a part of this.
- **Github**: We looked into our issues and took the ones that spoke to us. Four issues were taken. Feel free to add, change, remove issues so they match what you do. Discuss in the issue what DoD would be. Use this group, have meetings in-between our meetings, do what you need to move your issue forward!
- The **follow-up meeting** with members from Front x on June 17: We will show them our set up with Slack, Github and the issues we have. Encourage people to add more issues. Talk shortly about the issues we are focusing on.
- Joacim showed the **component page** in the new Design Library and asked for feedback on how the link to resp repos should look. Join his issue to talk more about this!
- **Next meeting** is June 25. Robert will show us Bootstrap. Anyone that wants to show progress on their issue is welcome to it. Probably the last meeting before the summer holidays (I will ask you then). Back late August.

**Comment by ulde01** [comment]
### Future of component libraries, meeting 2020-06-17
Anders S, Saulius, Robert H, Jocke, Leopold, Ulrika
 
**Purpose of meeting**
Follow-up on how the smaller team has progressed in addressing issues that contribute how front-end development and design can work better together with common components.

**Last time we talked about…** 
Reminder: Background and why a design system, Concept of Design Library and communities contributing, Obstacles today, How should it work, Brainstorm on Todo’s

**What have we done since May 12?**
- Frontend Frameworks Coordination Team with “community managers”: Joacim (Vanilla), Robert (Bootstrap), Karolis (ng-material), Yousif (ng-component, react-components), Leopold, Ulrika (Design)
- Meeting routine of every second Thursday (with summer break)
- Slack channel #design-library-dev
- We have had two meetings:
May 28: Why do we need this, who do we do this for, what is our responsibility, what topics to address
June 11: Time allocation, issues added into Github, what issues to start with 

**Github repository**
https://github.com/sebgroup/design-library/projects/3
Everyone is welcome to add questions and feedback that would help the whole front-end community if we talked it out

**Other things**
- Who do you think should be approached about time allocation and organisation? CTO 
- How would you like to continue this forum?
- Discussion with architects Ulf and Niklas is coming up

**What are the next steps?**
- Use mail, Github or Slack #design-library for your input!
- We continue working with our issues, tbc after the summer
